
USE PetshopT;
GO
CREATE TABLE LOGIN(
	CODIGO INT NOT NULL IDENTITY,
	NOME VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	SENHA VARCHAR(50) NOT NULL,
	CONSTRAINT PK_LOGIN PRIMARY KEY(CODIGO)
);
GO
CREATE TABLE PET(
	CODIGO INT NOT NULL IDENTITY,
	NOME VARCHAR(50) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	SEXO CHAR(1) NOT NULL,
	TAMANHO VARCHAR(50) NOT NULL,
	RACA VARCHAR(50) NOT NULL,
	CONSTRAINT PK_PET PRIMARY KEY(CODIGO),

);
GO
CREATE TABLE SERVICO(
	CODIGO INT NOT NULL IDENTITY,
	NOME VARCHAR(50) NOT NULL,
	PRECO VARCHAR(50) NOT NULL,
	CONSTRAINT PK_SERVICO PRIMARY KEY(CODIGO),
);
GO
CREATE TABLE HORARIO(
	--CODIGO INT NOT NULL IDENTITY,
	DATA_AGENDAMENTO DATE NOT NULL,
	HORA_AGENDAMENTO VARCHAR(50) NOT NULL,
	CODIGO_SERVICO INT NOT NULL,
	CODIGO_PET INT NOT NULL,
	--CONSTRAINT PK_DEPENDENTE PRIMARY KEY(CODIGO),
	CONSTRAINT FK_HORARIO_PET FOREIGN KEY(CODIGO_PET)
		REFERENCES PET(CODIGO),
	CONSTRAINT FK_HORARIO_SERVICO FOREIGN KEY(CODIGO_SERVICO)
		REFERENCES SERVICO(CODIGO)
);