CREATE DATABASE PETSHOP1;
GO
USE PETSHOP1;
GO
CREATE TABLE LOGIN(
	CODIGO INT NOT NULL IDENTITY,
	USUARIO_LOG VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	SENHA VARCHAR(50) NOT NULL,
	CODIGO_FUNCIONARIO INT NOT NULL,
	CONSTRAINT PK_LOGIN PRIMARY KEY(CODIGO),
	CONSTRAINT FK_LOGIN_FUNCIONARIO FOREIGN KEY(CODIGO)
		REFERENCES FUNCIONARIO(CODIGO),
);
GO
CREATE TABLE FUNCIONARIO(
	CODIGO INT NOT NULL IDENTITY,
	NOME_FUN VARCHAR(50) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	SEXO CHAR(1) NOT NULL,
	CPF VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	TELEFONE VARCHAR(50) NOT NULL,
	CONSTRAINT PK_FUNCIONARIO PRIMARY KEY(CODIGO),

);

GO
CREATE TABLE PET(
	CODIGO INT NOT NULL IDENTITY,
	NOME_PET VARCHAR(50) NOT NULL,
	DATA_NASCIMENTO DATE NULL,
	SEXO CHAR(1) NOT NULL,
	TAMANHO VARCHAR(50) NULL,
	RACA VARCHAR(50) NULL,
	RESTRICOES CHAR(1) NOT NULL,
	DESC_RESTRICOES VARCHAR(200) NULL,
	CONSTRAINT PK_PET PRIMARY KEY(CODIGO),
);
GO
CREATE TABLE CLIENTE(
	CODIGO INT NOT NULL IDENTITY,
	NOME_CLI VARCHAR(50) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	SEXO CHAR(1) NOT NULL,
	CPF VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	TELEFONE VARCHAR(50) NOT NULL,
	CODIGO_PET INT NOT NULL,
	CONSTRAINT PK_FUNCIONARIO1 PRIMARY KEY(CODIGO),
	CONSTRAINT FK_CLIENTE_PET FOREIGN KEY(CODIGO_PET)
		REFERENCES PET(CODIGO)

);
GO
CREATE TABLE TIPO_SERVICO(
	CODIGO INT NOT NULL IDENTITY,
	NOME_TIPO VARCHAR(50) NOT NULL,
	DESC_SERVICO VARCHAR(200) NULL,
	CONSTRAINT PK_SERVICO PRIMARY KEY(CODIGO),
);

GO
CREATE TABLE SERVICO(
	CODIGO INT NOT NULL IDENTITY,
	CODIGO_TIPO_SER INT NOT NULL,
	PRECO VARCHAR(50) NOT NULL,
	CONSTRAINT PK_SERVICO1 PRIMARY KEY(CODIGO),
	CONSTRAINT FK_TIPO_SERVICO FOREIGN KEY(CODIGO_TIPO_SER)
		REFERENCES TIPO_SERVICO(CODIGO),
);
GO
CREATE TABLE AGENDAMENTO(
	CODIGO INT NOT NULL IDENTITY,
	DATA_AGENDAMENTO DATE NOT NULL,
	HORA_AGENDAMENTO TIME NOT NULL,
	CODIGO_SERVICO INT NOT NULL,
	CODIGO_PET INT NOT NULL,
	CONSTRAINT PK_DEPENDENTE PRIMARY KEY(CODIGO),
	CONSTRAINT FK_HORARIO_PET FOREIGN KEY(CODIGO_PET)
		REFERENCES PET(CODIGO),
	CONSTRAINT FK_HORARIO_SERVICO FOREIGN KEY(CODIGO_SERVICO)
		REFERENCES SERVICO(CODIGO)
);