//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ANIMALE_PETSHOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENDAMENTO
    {
        public int CODIGO { get; set; }
        public System.DateTime DATA_AGENDAMENTO { get; set; }
        public System.TimeSpan HORA_AGENDAMENTO { get; set; }
        public int CODIGO_SERVICO { get; set; }
        public int CODIGO_PET { get; set; }
    
        public virtual PET PET { get; set; }
        public virtual SERVICO SERVICO { get; set; }
    }
}
