//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ANIMALE_PETSHOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGIN
    {
        public int CODIGO { get; set; }
        public string USUARIO_LOG { get; set; }
        public string EMAIL { get; set; }
        public string SENHA { get; set; }
    }
}
